### ISSUE TITLE
Autenticação de Usuário (Login com Conta UFF)

### ISSUE THREAD

**Issue by Roberto-deP-Martins** [Roberto-deP-Martins/Balcao-UFF#7]
Implementar a funcionalidade de login de usuários usando a autenticação da UFF (OAuth2, OpenID ou similar).

**Critérios de Aceitação:** Funcionalidade de login pronta e integrada, disponível para testes. Documentação da API de autenticação no Swagger.

**Comment by JHONHP7** [comment]
***Duração issue: 24h.***
